/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Trans extends javax.swing.JFrame {
    String username;
    void tampilTabel(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tubespbo","root","");
            //mysql query to run
            Statement stm = con.createStatement();

            String sql = "select * from transaksi";
            ResultSet result = stm.executeQuery(sql);
            DefaultTableModel model = (DefaultTableModel) rumah_tb.getModel();
            while(result.next()){
                model.addRow(new Object[]{result.getString(1),result.getString(4),result.getString(2),result.getString(3),result.getString(5),result.getString(6)});
                rumah_tb.setModel(model);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    /**
     * Creates new form Trans
     */
     public Trans(String username) {
         initComponents();
         this.username = username;
         tampilTabel();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username_tx = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rumah_tb = new javax.swing.JTable();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nama_pembeli_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        view_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id_rumah_tf = new javax.swing.JTextField();
        cicilan_rb = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABEL TRANSAKSI");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Hello,");

        username_tx.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        username_tx.setText("nama");

        rumah_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID rumah", "Nama Pembeli", "Metode Pembayaran", "Harga", "Created At"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rumah_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rumah_tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rumah_tb);
        if (rumah_tb.getColumnModel().getColumnCount() > 0) {
            rumah_tb.getColumnModel().getColumn(5).setResizable(false);
        }

        delete_btn.setText("DELETE");
        delete_btn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        save_btn.setText("SAVE");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Nama Pembeli");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Metode Pembayaran");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        view_btn.setText("HOMEPAGE");
        view_btn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("ID Rumah");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        id_rumah_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_rumah_tfActionPerformed(evt);
            }
        });

        cicilan_rb.setText("Cicilan");
        cicilan_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicilan_rbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username_tx, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(save_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama_pembeli_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_rumah_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cicilan_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(13, 13, 13)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(username_tx)
                        .addComponent(jLabel2))
                    .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_rumah_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_pembeli_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cicilan_rb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        try{
            if(rumah_tb.getSelectedRowCount()==1){
                DefaultTableModel model = (DefaultTableModel) rumah_tb.getModel();
                String idDb = model.getValueAt(rumah_tb.getSelectedRow(), 0).toString();
                String idRumah = id_rumah_tf.getText();
                String nama_pembeli = nama_pembeli_tf.getText();


                
            String sql = "update transaksi set id_rumah='"+idRumah+"', pembeli='"+nama_pembeli+"' where id='"+idDb+"'";

    
            Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tubespbo","root","");

                Statement stm = con.createStatement();
             stm.executeUpdate(sql);

                JOptionPane.showConfirmDialog(null, "Data berhasil diupdate", "Result", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
                reset();
            }else{
                if(rumah_tb.getRowCount()==0){
                    JOptionPane.showConfirmDialog(null, "Data di dalam tabel masih kosong", "Result", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
                }else{
                    JOptionPane.showConfirmDialog(null, "Pilih salah satu baris untuk diupdate", "Result", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel) rumah_tb.getModel();
            String idDb = model.getValueAt(rumah_tb.getSelectedRow(), 0).toString();
            
            String sql = "DELETE FROM transaksi WHERE id='"+idDb+"'";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tubespbo","root","");

            Statement stm = con.createStatement();
            stm.executeUpdate(sql);
            JOptionPane.showConfirmDialog(null, "Data berhasil dihapus", "Result", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
            reset();
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_delete_btnActionPerformed
    
    private String cicil(String idRumah, String nama_pembeli,String metode, String sql,int foundType){
        int harga = (foundType / 100 + foundType)/120;
        return "insert into transaksi(id_rumah,pembeli,metode_pembayaran, harga) values ('"+idRumah+"','"+nama_pembeli+"','"+metode+"','"+harga+"')";
    }
    private String cicil(String idRumah, String nama_pembeli, String sql,int foundType){
        String metode = "Cash";
        return "insert into transaksi(id_rumah,pembeli,metode_pembayaran, harga) values ('"+idRumah+"','"+nama_pembeli+"','"+metode+"','"+foundType+"')";
    }
    
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "";
            String metode = "Cash";
            String idRumah = id_rumah_tf.getText();
            String nama_pembeli = nama_pembeli_tf.getText();
            Boolean metode_pembayaran = cicilan_rb.isSelected();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tubespbo","root","");
            Statement stm = con.createStatement();
            String getSqlHarga = "select harga from rumah where id_rumah='"+idRumah+"'";
            ResultSet result = stm.executeQuery(getSqlHarga);
            if(result.first()){
                int foundType = result.getInt(1);
                  
            
                if(metode_pembayaran){
                    metode = "Cicilan";
                    sql = cicil(idRumah, nama_pembeli,metode, sql, foundType);
                    
                }else{
                    sql = cicil(idRumah, nama_pembeli, sql, foundType);
                }
               
            }
            Class.forName("com.mysql.jdbc.Driver");          
            JOptionPane.showConfirmDialog(null, "Data berhasil disimpan", "Result", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE);
            reset();
            stm.executeUpdate(sql);
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void rumah_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rumah_tbMouseClicked
    //    // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) rumah_tb.getModel();
        
        String id_rumah = model.getValueAt(rumah_tb.getSelectedRow(), 1).toString();
        String nama = model.getValueAt(rumah_tb.getSelectedRow(), 2).toString();
        String metode_pembayaran = model.getValueAt(rumah_tb.getSelectedRow(), 3).toString();
        String created_at = model.getValueAt(rumah_tb.getSelectedRow(), 4).toString();
        
      id_rumah_tf.setText(id_rumah);
      nama_pembeli_tf.setText(nama);
       
    }//GEN-LAST:event_rumah_tbMouseClicked

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        dispose();
        Homepage homepage = Homepage(username);
                homepage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_view_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_rumah_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_rumah_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_rumah_tfActionPerformed

    private void cicilan_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicilan_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cicilan_rbActionPerformed
    private void reset(){

        String nama_pembeli = nama_pembeli_tf.getText();
       // String metode_pembayaran = metode_pembayaran_tf.getText();
        
        DefaultTableModel model = (DefaultTableModel) rumah_tb.getModel();
        model.setRowCount(0);
        tampilTabel();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton cicilan_rb;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField id_rumah_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_pembeli_tf;
    private javax.swing.JTable rumah_tb;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel username_tx;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
